<?xml version="1.0" encoding="utf-8"?><Database Name="EasyPartner" ContextNamespace="MvcBlanket.Security.DataAccess" Class="SecurityDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=sqlserver;Initial Catalog=database;Integrated Security=True" SettingsObjectName="MvcBlanket.Security.Properties.Settings" SettingsPropertyName="SecurityConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Security.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Role_User2Role" Member="User2Roles" ThisKey="Id" OtherKey="RoleId" Type="User2Role" />
    </Type>
  </Table>
  <Table Name="Security.User2Role" Member="User2Roles">
    <Type Name="User2Role">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Access" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Association Name="Role_User2Role" Member="Role" ThisKey="RoleId" OtherKey="Id" Type="Role" IsForeignKey="true" />
      <Association Name="User_User2Role" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Security.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.Data.Linq.Binary" DbType="Binary(64)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Salt" Type="System.Byte[]" DbType="binary(8) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SecondName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EMail" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="RegDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLogon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastActivity" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsGroup" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ActivationKey" Type="System.Guid" DbType="uniqueidentifier" CanBeNull="false" />
      <Association Name="User_User2Role" Member="User2Roles" ThisKey="Id" OtherKey="UserId" Type="User2Role" />
      <Association Name="User_User" Member="Users" ThisKey="Id" OtherKey="GroupId" Type="User" />
      <Association Name="User_User2ParentUser" Member="ChildUsers" ThisKey="Id" OtherKey="ParentUserId" Type="User2ParentUser" />
      <Association Name="User_User2ParentUser1" Member="ParentUsers" ThisKey="Id" OtherKey="UserId" Type="User2ParentUser" />
      <Association Name="User_User" Member="Group" Storage="_User1" ThisKey="GroupId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Security.User2ParentUser" Member="User2ParentUsers">
    <Type Name="User2ParentUser">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_User2ParentUser" Member="ParentUser" ThisKey="ParentUserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_User2ParentUser1" Member="ChildUser" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>